add Default value of waiting time
erda-project/erda-actions pull request #105
Opened 2021-07-26 02:17 UTC by pipipipipi43

add Default value of waiting time

2021-07-26 03:03 UTC, sfwn requested changes

2021-07-26 03:03 UTC, sfwn commented on actions/manual-review/1.0/internal/conf/conf.go
> +	WaitingTime int      `env:"ACTION_WAITING_TIME" default:"5"`
missing unit. 5ms or 5s or anything else?

2021-07-26 03:03 UTC, sfwn commented on actions/manual-review/1.0/dice.yml
> +    image: registry.erda.cloud/erda-actions/manual-review-action:20210726-fc23bef
Image's commit is not correct.
You should build image after this pr is merged.

2021-07-26 06:13 UTC, pipipipipi43 commented on actions/manual-review/1.0/internal/conf/conf.go
> +	WaitingTime int      `env:"ACTION_WAITING_TIME" default:"5"`
Just an int type, In the expression time.Duration(waitingTime) * time.Second,it will be converted to the format of seconds

2021-07-28 12:36 UTC, sfwn requested changes

2021-07-28 12:36 UTC, sfwn commented on actions/manual-review/1.0/internal/conf/conf.go
> +	WaitingTime int      `env:"ACTION_WAITING_TIME" default:"5"` // 单位: S
action:
  params:
    wait_time_interval_sec: 5

2021-07-28 12:36 UTC, sfwn commented on actions/manual-review/1.0/dice.yml
> +    image: registry.erda.cloud/erda-actions/manual-review-action:20210726-fc23bef
delete it

2021-08-10 02:24 UTC, closed without merging