add testscene-run action
erda-project/erda-actions pull request #106
Opened 2021-07-26 06:26 UTC by pipipipipi43

Execute the corresponding pipeline according to the scene name and parameter configuration, and then wait for the execution to complete

2021-07-27 13:03 UTC, sfwn commented
add a logo for this action.

2021-07-27 13:04 UTC, sfwn requested changes

2021-07-27 13:04 UTC, sfwn commented on actions/testscene-run/1.0/spec.yml
> +supportedVersions:
useErdaVersions

2021-07-27 13:04 UTC, sfwn commented on actions/testscene-run/1.0/spec.yml
> +supportedVersions:
useProtocol

2021-07-29 09:41 UTC, pipipipipi43 commented
related erda pr: https://github.com/erda-project/erda/pull/1218

2021-07-29 10:57 UTC, sfwn approved these changes

2021-07-29 12:17 UTC, merged