fix: polish the print of dice action
erda-project/erda-actions pull request #131
Opened 2021-08-05 11:26 UTC by littlejiancc

**What type of this PR**
/kind polish

**What this PR does / why we need it:**
fix: polish the print of dice action

**Which issue(s) this PR fixes:**
https://erda.cloud/erda/dop/projects/387/issues/bug?id=204242&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzFdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG

reviewer: @sfwn

2021-08-05 13:29 UTC, sfwn requested changes

2021-08-05 13:29 UTC, sfwn commented on actions/dice/1.0/internal/dice/client.go
> +	logrus.Infof(" clusterName: %s", req.ClusterName)
I think `C` should be uppercase, the same with others.

2021-08-05 13:29 UTC, sfwn commented on actions/dice/1.0/internal/dice/client.go
> +		logrus.Errorf("deploy to dice failed! response err: %v.", err)
no need end dot.

2021-08-05 13:29 UTC, sfwn commented on actions/dice/1.0/internal/dice/client.go
> +		logrus.Infof(" runtime: %+v", r.Data.Runtime)
Do not use %+v.
Print necessary fields only. Or use json format.

2021-08-05 13:29 UTC, sfwn commented on actions/dice/1.0/internal/dice/client.go
> +	logrus.Infof(" err: %+v", r.Err)
Err may be nil.

2021-08-06 01:49 UTC, littlejiancc commented on actions/dice/1.0/internal/dice/client.go
> +		logrus.Infof(" runtime: %+v", r.Data.Runtime)
the Runtime is interface{}

2021-08-06 01:50 UTC, littlejiancc commented on actions/dice/1.0/internal/dice/client.go
> +	logrus.Infof(" clusterName: %s", req.ClusterName)
done

2021-08-06 02:18 UTC, littlejiancc commented on actions/dice/1.0/internal/dice/client.go
> +		logrus.Errorf("deploy to dice failed! response err: %v.", err)
done

2021-08-06 02:18 UTC, littlejiancc commented on actions/dice/1.0/internal/dice/client.go
> +	logrus.Infof(" clusterName: %s", req.ClusterName)
all update to lowercase

2021-08-06 02:18 UTC, littlejiancc commented on actions/dice/1.0/internal/dice/client.go
> +	logrus.Infof(" err: %+v", r.Err)
done

2021-08-06 02:21 UTC, littlejiancc commented on actions/dice/1.0/internal/dice/deploy.go
> +	logrus.Infof("msg=\"deploy starting... ##to_link:applicationId:%d,runtimeId:%d,deploymentId:%d\"",
done

2021-08-06 03:51 UTC, sfwn approved these changes

2021-08-06 03:51 UTC, merged