Add new error message for docker push
erda-project/erda-actions pull request #162
Opened 2021-08-27 08:03 UTC by pipipipipi43

Add new error message for docker push
[erda link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=201539&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDA4MDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=REQUIREMENT)

buildpack action test
<img width="1127" alt="ggg" src="https://user-images.githubusercontent.com/32703277/131666932-7ff36d73-7150-4a5c-8a97-0fb67b46851e.png">
<img width="398" alt="ffff" src="https://user-images.githubusercontent.com/32703277/131666951-5000df84-1eb2-4c6a-85be-587f3e1e0c73.png">

dockerfile aciton test
<img width="1115" alt="hhhhh" src="https://user-images.githubusercontent.com/32703277/131667049-b809b3dd-d0af-4f71-a553-6f921748871b.png">
<img width="408" alt="hhhh" src="https://user-images.githubusercontent.com/32703277/131667056-b114811e-b2f6-45f9-9d3f-dcad5180c308.png">

2021-09-01 11:08 UTC, kakj-go commented on actions/buildpack-aliyun/1.0/internal/run/pack/pack.go
> +	err = docker.DockerPush(conf.EasyUse().CalculatedCacheImage, wd)
have problem，the logic is different

2021-09-01 11:08 UTC, kakj-go commented on actions/buildpack/1.0/internal/run/pack/pack.go
> +	err = docker.DockerPush(conf.EasyUse().CalculatedCacheImage, wd)
have problem，the logic is different

2021-09-02 03:00 UTC, sfwn requested changes

2021-09-02 03:00 UTC, sfwn commented on actions/buildpack/1.0/internal/run/pack/pack.go
> +	if errors.Len() > 0 {
abstract a method for 405 handler.

2021-09-02 06:53 UTC, pipipipipi43 commented on actions/buildpack/1.0/internal/run/pack/pack.go
> +	if errors.Len() > 0 {
done

2021-09-02 06:56 UTC, pipipipipi43 commented
Tested in dev :[test](https://erda.dev.terminus.io/terminus/dop/projects/1/apps/3/pipeline?nodeId=MS8zL3RyZWUvZGV2ZWxvcC8uZGljZS9waXBlbGluZXMvYnVpbGRwYWNrLnltbA%3D%3D&pipelineID=14540)

2021-09-02 06:56 UTC, sfwn approved these changes

2021-09-02 06:57 UTC, sfwn commented
/approve

2021-09-02 06:57 UTC, merged