update nodejs use docs, add dest_dir annotation
erda-project/erda-actions pull request #186
Opened 2021-09-10 02:04 UTC by kakj-go

## Description

update nodejs use docs, add dest_dir annotation

## Checklist

 - [] I made sure to check the compatibility of the erda version statemented in the action's spec.yml.
 - [ ] My change is adequately tested.

2021-09-10 02:08 UTC, sfwn requested changes

2021-09-10 02:08 UTC, sfwn commented on actions/js-build/1.0/README.md
> +            - ${js-build}/dist:/usr/share/nginx/html/   # dist 是使用 npm build 生成出来的文件名称
dist 是使用 npm run build 生成出来的目录，常见的目录有：public、dist 等

2021-09-11 14:29 UTC, Effet submitted a review, later dismissed

2021-09-11 14:29 UTC, Effet commented on actions/js/1.0/README.md
> +    container_type: herd
bad format, tail space

2021-09-26 10:56 UTC, sfwn approved these changes

2021-09-26 10:57 UTC, sfwn commented
/approve

2021-09-26 10:57 UTC, merged