Spec yml i18n example, readme
erda-project/erda-actions pull request #329
Opened 2022-01-12 05:48 UTC by shuofan

## Description

Spec yml i18n example, readme

## Checklist

 - [x] I made sure to check the compatibility of the erda version statemented in the action's spec.yml.
 - [x] My change is adequately tested.

2022-01-13 13:33 UTC, Effet requested changes

2022-01-13 13:33 UTC, Effet commented on actions/api-test/2.0/spec.yml
> +      not_contains, belong, not_belong, empty, not_empty, exist, not_exist
broken line

2022-01-13 13:33 UTC, Effet commented on actions/api-test/2.0/spec.yml
> +      等
broken line

2022-01-13 13:33 UTC, Effet commented on actions/archive-release/1.0/spec.yml
> +      。
broken line

2022-01-14 09:36 UTC, shuofan commented on actions/api-test/2.0/spec.yml
> +      not_contains, belong, not_belong, empty, not_empty, exist, not_exist
Solve all problems

2022-01-17 03:55 UTC, Effet requested changes

2022-01-17 03:55 UTC, Effet commented on actions/publish-api-asset/1.0/spec.yml
> +    required: true
tailing space

2022-01-17 03:55 UTC, Effet commented on actions/publish-api-asset/1.0/spec.yml
> +    required: true
tailing space

2022-01-17 03:55 UTC, Effet commented on actions/push-extensions/1.0/spec.yml
> +
tailing space

2022-01-17 06:23 UTC, shuofan commented on actions/publish-api-asset/1.0/spec.yml
> +    required: true
done

2022-01-17 06:44 UTC, Effet approved these changes

2022-01-17 06:44 UTC, merged