retag image registry
erda-project/erda-actions pull request #33
Opened 2021-05-18 10:52 UTC by Muzry

- retag image registry

2021-05-19 03:50 UTC, Muzry commented
/cc @sfwn

2021-05-19 05:38 UTC, luobily requested changes

2021-05-19 05:38 UTC, luobily commented on actions/java-agent/1.0/dice.yml
> +      JAVA_AGENT_OPTS: -javaagent:/erda/spot-agent/spot-agent.jar -javaagent:/erda/spot-agent/spot-profiler.jar
check cmd

2021-05-19 05:38 UTC, luobily commented on actions/java-agent/1.0/dice.yml
> +      JAVA_AGENT_OPTS: -javaagent:/erda/spot-agent/spot-agent.jar -javaagent:/erda/spot-agent/spot-profiler.jar
This directory is not exist

2021-05-19 05:38 UTC, luobily commented
cc @sfwn

2021-05-19 06:02 UTC, sfwn requested changes

2021-05-19 06:02 UTC, sfwn commented on dockerfiles/terminus-herd/herd.1.1.9-beta.2/deploy.sh
> +image=erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/terminus-herd:1.1.9-beta.2
not exist

2021-05-19 07:19 UTC, sfwn requested changes

2021-05-19 07:19 UTC, sfwn commented on actions/buildpack-aliyun/1.0/Dockerfile
> +FROM erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/centos:7
not exist

2021-05-19 07:19 UTC, sfwn commented on actions/buildpack-aliyun/1.0/bp/java/build/maven/Dockerfile
> +FROM {{BP_DOCKER_BASE_REGISTRY}}/erda/terminus-maven:3-jdk-8-alpine
rebuild buildpack action image

2021-05-19 07:19 UTC, sfwn commented on actions/buildpack-aliyun/1.0/bp/java/pack/springboot-asia/Dockerfile
> +FROM {{BP_DOCKER_BASE_REGISTRY}}/erda/terminus-openjdk:v1.8.0.242-asia
rebuild related action

2021-05-19 07:19 UTC, sfwn commented on actions/buildpack/1.0/bp/java/build/maven/Dockerfile
> +FROM {{BP_DOCKER_BASE_REGISTRY}}/erda/terminus-maven:3-jdk-8-alpine
rebuild related action

2021-05-19 07:19 UTC, sfwn commented on actions/custom-script/1.0/Dockerfile
> +FROM erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/git-golang-image:1.1
not exist

2021-05-19 07:19 UTC, sfwn commented on actions/gitbook/1.0/comp/Dockerfile
> +FROM {{CENTRAL_REGISTRY}}/erda/terminus-nginx:0.2
rebuild action image.

2021-05-19 07:19 UTC, sfwn commented on actions/java-build/1.0/internal/test.sh
> +docker run -v /var/run/docker.sock:/var/run/docker.sock -v /root/demo-notice:/root -e ACTION_WORKDIR=/root -e ACTION_OPTIONS="-am -pl cp-notice-starter -Dmaven.test.skip=true" -e ACTION_TARGET=cp-not
erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/mvn-action:v1.0

not exist

2021-05-19 07:19 UTC, sfwn commented on actions/java/1.0/comp/openjdk/Dockerfile
> +FROM {{CENTRAL_REGISTRY}}/erda/terminus-openjdk:$CONTAINER_VERSION
rebuild action image

2021-05-19 07:19 UTC, sfwn commented on actions/js/1.0/comp/herd/Dockerfile
> +FROM {{CENTRAL_REGISTRY}}/erda/terminus-herd:1.1.8-node12
rebuild action image

2021-05-19 07:19 UTC, sfwn commented on actions/php/1.0/comp/Dockerfile
> +FROM {{CENTRAL_REGISTRY}}/erda/terminus-php-apache:{{PHP_VERSION}}
rebuild action image

2021-05-19 07:19 UTC, sfwn commented on actions/release/1.0/comp/migration/Dockerfile
> +FROM erda-registry.cn-hangzhou.cr.aliyuncs.com/erda/migration:1.0.2
rebuild action image

2021-06-09 05:54 UTC, sfwn approved these changes

2021-06-09 05:54 UTC, merged