feat: show specific deploy error message
erda-project/erda-actions pull request #35
Opened 2023-12-06 08:07 UTC by CeerDecy

## Description
dice1.0 and dice2.0 : add deploy failcase to metaData

## Checklist

2023-12-06 08:23 UTC, iutx reviewed
@CeerDecy

2023-12-06 08:23 UTC, iutx commented on actions/dice/2.0/internal/pkg/dice/deploy/status_check.go
> +	// 以下代码在上面用defer执行
Remove unused code.

2023-12-08 03:37 UTC, CeerDecy commented on actions/dice/2.0/internal/pkg/dice/deploy/status_check.go
> +	// 以下代码在上面用defer执行
@iutx done

2023-12-20 01:27 UTC, iutx commented on actions/dice/2.0/internal/pkg/dice/deploy/status_check.go
> +		logrus.Infof("====> default")
@CeerDecy cc

2023-12-25 07:42 UTC, iutx commented
/approve

2023-12-25 07:53 UTC, iutx submitted a review, later dismissed
LGTM @sfwn 
[related pr](https://github.com/erda-project/erda/pull/6169)

2024-03-06 02:26 UTC, sfwn requested changes

2024-03-06 02:26 UTC, sfwn commented on actions/dice/2.0/internal/pkg/dice/deploy/status_check.go
> +				logrus.Error("failed to check deploy ", err)
use `Errorf`

2024-03-06 03:25 UTC, sfwn approved these changes

2024-03-06 03:25 UTC, sfwn commented
/approve

2024-03-06 03:25 UTC, merged