add sonar action version 2.0
erda-project/erda-actions pull request #377
Opened 2022-03-03 07:51 UTC by chengjoey

## Description

[erda issue link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=287301&iterationID=1115&pId=0&type=TASK)

## Checklist

 - [ ] I made sure to check the compatibility of the erda version statemented in the action's spec.yml.
 - [ ] My change is adequately tested.

2022-03-03 08:31 UTC, Effet commented
how to compatible with 1.0?

2022-03-04 07:56 UTC, chengjoey commented
> how to compatible with 1.0?

![image](https://user-images.githubusercontent.com/30427474/156722656-2c719ea8-9041-4174-a69c-2a5419ce12ac.png)
set 1.0 as default

2022-03-07 03:17 UTC, Effet requested changes

2022-03-07 03:17 UTC, Effet commented on actions/sonar/2.0/internal/web_api.go
> +	}
what these code use for?

2022-03-07 09:27 UTC, chengjoey commented on actions/sonar/2.0/internal/web_api.go
> +	}
adjuested, removed useless code

2022-03-07 09:28 UTC, chengjoey commented on actions/sonar/2.0/internal/web_api.go
> +	}
![image](https://user-images.githubusercontent.com/30427474/157004141-add3c599-04a8-490e-abd4-759b68741700.png)

2022-03-07 10:04 UTC, Effet requested changes

2022-03-07 10:04 UTC, Effet commented on actions/sonar/2.0/internal/analysis.go
> +	}
I suggest "one func do one thing", and `Analysis` should just return the analysis result, you can move this gate check logic to outside.

2022-03-07 10:56 UTC, chengjoey commented on actions/sonar/2.0/internal/application.go
> +func getApplication(cfg *Conf) (*apistructs.ApplicationDTO, error) {
non

2022-03-09 11:26 UTC, Effet requested changes

2022-03-09 11:26 UTC, Effet commented on actions/sonar/2.0/README.md
> +
give another simple example which sonar_host_url in application setting page

2022-03-09 11:26 UTC, Effet commented on actions/sonar/2.0/internal/pkg/conf.go
> +	ProjectKey string `env:"ACTION_PROJECT_KEY"`
`ACTION_SONAR_PROJECT_KEY` maybe better

2022-03-09 11:26 UTC, Effet commented on actions/sonar/2.0/internal/pkg/sonar.go
> +var (
is there any sonar go sdk to use?

2022-03-09 11:26 UTC, Effet commented on pkg/envconf/platform.go
> +	Debug bool `env:"ACTION_DEBUG" default:"false"`
it looks like not a platform param?

2022-03-14 02:46 UTC, chengjoey commented on actions/sonar/2.0/README.md
> +
maybe add example when `erda-cli` can be used

2022-03-14 03:32 UTC, chengjoey commented on actions/sonar/2.0/internal/pkg/conf.go
> +	ProjectKey string `env:"ACTION_PROJECT_KEY"`
adjusted

2022-03-14 03:32 UTC, chengjoey commented on actions/sonar/2.0/internal/pkg/sonar.go
> +var (
not found golang sonar sdk

2022-03-14 03:32 UTC, chengjoey commented on pkg/envconf/platform.go
> +	Debug bool `env:"ACTION_DEBUG" default:"false"`
adjusted, move this to action param

2022-03-14 06:36 UTC, chengjoey commented on pkg/meta/result_meta.go
> +func (r *ResultMetas) Store(metaFilepath string) error {
impl `logCollector` and `fileCollector` to collect result meta, default use `action meta:k=v`
![image](https://user-images.githubusercontent.com/30427474/158117715-c9b64ef2-2319-4eac-ad5d-433411ab91c4.png)

2022-03-18 05:50 UTC, Effet requested changes

2022-03-18 05:50 UTC, Effet commented on pkg/envconf/platform.go
> +	OrgId  uint64 `env:"DICE_ORG_ID"`
it should be `OrgID`

2022-03-18 05:50 UTC, Effet commented on actions/sonar/2.0/internal/pkg/sonar.go
> +	"github.com/erda-project/erda/pkg/http/httpclient"
please format the import order

2022-03-18 07:45 UTC, Effet approved these changes

2022-03-18 07:45 UTC, merged