feature: add some params for java-dependency-check action.
erda-project/erda-actions pull request #445
Opened 2022-06-20 07:38 UTC by xautjzd

## Description

Add some params for java-dependency-check action.

## Checklist

1. Specify dependency-check maven plugin goal.
2. Specify CVSS score.

2022-06-21 02:03 UTC, sfwn requested changes

2022-06-21 02:03 UTC, sfwn commented on actions/java-dependency-check/1.0/internal/pkg/conf/conf.go
> +	FailBuildOnCVSS      float64 `env: "ACTION_FAIL_BUILD_ON_CVSS" default:"9.0"`
remove blank at `env: "`

2022-06-21 02:03 UTC, sfwn commented on actions/java-dependency-check/1.0/spec.yml
> +    params.goal.desc: 用户指定漏洞检测插件的 goal, 可选值有 aggregate, check
add more description for aggregate and check

2022-06-21 02:03 UTC, sfwn commented on actions/java-dependency-check/1.0/spec.yml
> +    params.goal.desc: 用户指定漏洞检测插件的 goal, 可选值有 aggregate, check
adjust README.md

2022-06-21 02:33 UTC, xautjzd commented
fixed

2022-07-05 06:51 UTC, huangzx618 commented on actions/java-dependency-check/1.0/spec.yml
> +    params.goal.desc: 用户指定漏洞检测插件的 goal, 可选值有 aggregate, check
do you mean this?
--用户指定漏洞检测报告的目标形式
* aggregate：创建汇总的依赖性检查报告
* check：在指定目标内创建dependency-check-report.html

2022-11-09 02:36 UTC, sfwn submitted a review, later dismissed

2022-11-09 03:57 UTC, sfwn approved these changes

2022-11-09 03:57 UTC, sfwn commented
/approve

2022-11-09 03:58 UTC, merged