feat: add semgrep action
erda-project/erda-actions pull request #477
Opened 2022-08-17 05:35 UTC by chengjoey

## Description
add semgrep action

## Checklist

 - [ ] I made sure to check the compatibility of the erda version statemented in the action's spec.yml.
 - [ ] My change is adequately tested.

2022-08-17 05:43 UTC, Effet requested changes

2022-08-17 05:43 UTC, Effet commented on actions/semgrep/1.0/spec.yml
> +    displayName: Sonar Code Quality Check
bad name

2022-08-17 05:48 UTC, chengjoey commented on actions/semgrep/1.0/spec.yml
> +    displayName: Sonar Code Quality Check
adjusted

desc: Code Analysis at Ludicrous Speed, find bugs, run security scans in CI, and enforce security standards across your organization.

2022-08-19 03:58 UTC, Effet requested changes

2022-08-19 03:58 UTC, Effet commented on actions/semgrep/1.0/README.md
> +          - --error
given the best simple practice, and append a more scene-related case. please do not mix all option in one example.

2022-08-19 06:01 UTC, chengjoey commented on actions/semgrep/1.0/README.md
> +          - --error
add two best practrice
1. use auto rule
2. custom rule file

2022-08-19 06:02 UTC, chengjoey commented on actions/semgrep/1.0/README.md
> +          - --error
add introduction to common optional parameters

2022-08-19 07:30 UTC, Effet approved these changes

2022-08-19 07:30 UTC, merged