feat: use buildx support multi-arch image
erda-project/erda-actions pull request #516
Opened 2023-03-13 07:03 UTC by chengjoey

## Description

use buildx support multi-arch image

## Checklist

 - [ ] I made sure to check the compatibility of the erda version statemented in the action's spec.yml.
 - [ ] My change is adequately tested.

2023-03-13 07:12 UTC, sfwn requested changes

2023-03-13 07:12 UTC, sfwn commented on Makefile
> +	docker buildx create --name erda-actions
you should create buildx container Idempotently

2023-03-13 08:47 UTC, chengjoey commented on Makefile
> +	docker buildx create --name erda-actions
done

2023-03-16 05:51 UTC, sfwn approved these changes

2023-03-16 05:51 UTC, sfwn commented
/approve

2023-03-16 05:51 UTC, merged