feature: spec add supportedErdaVesions field
erda-project/erda-actions pull request #55
Opened 2021-06-16 11:05 UTC by sfwn

2021-06-16 11:06 UTC, sfwn commented
https://github.com/erda-project/erda-actions/pull/55

2021-06-17 03:08 UTC, Effet requested changes
missing supportedErdaVersions

2021-06-17 03:10 UTC, Effet requested changes

2021-06-17 03:10 UTC, Effet commented on actions/docker-push/1.0/spec.yml
> +supportedVersions: # Deprecated. Please use supportedErdaVersions instead.
missing supportedErdaVersions

2021-06-17 03:10 UTC, Effet commented on actions/java-agent/1.0/spec.yml
> +supportedVersions: # Deprecated. Please use supportedErdaVersions instead.
missing supportedErdaVersions

2021-06-17 07:13 UTC, Effet approved these changes

2021-06-17 07:13 UTC, Effet commented
/approve

2021-06-17 07:13 UTC, merged